// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnuftyafezojmrmbkgfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZudWZ0eWFmZXpvam1ybWJrZ2ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjAyNDQsImV4cCI6MjA2MDQ5NjI0NH0._UqAw8VL6dtgwBhk09-y5VvuJKlxqZRzXTKfZM9b2X4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);